[versions]
activity = "1.13.0"
hilt = "2.59.2"
kotlin = "2.3.21"
min-sdk = "26"
moshi = "1.15.2"
room = "2.8.4"
sdk-version = "37"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
appcompat = "androidx.appcompat:appcompat:1.8.0"
compose-bom = "androidx.compose:compose-bom:2026.08.00"
core = "androidx.test:core:1.7.0"
coroutines-test = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2"
datastore-preferences = "androidx.datastore:datastore-preferences:1.2.1"
espresso-core = "androidx.test.espresso:espresso-core:3.7.0"
firebase-bom = "com.google.firebase:firebase-bom:34.18.0"
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.4.0"
junit = "junit:junit:4.13.2"
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.11.0" }
material = { module = "androidx.compose.material:material" }
mockito-kotlin = "org.mockito.kotlin:mockito-kotlin:6.3.0"
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
navigation-compose = "androidx.navigation:navigation-compose:2.10.0"
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
rules = "androidx.test:rules:1.7.0"
runner = "androidx.test:runner:1.7.0"
ui = { module = "androidx.compose.ui:ui" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
google-services-plugin = "com.google.gms:google-services:4.5.0"
crashlytics-plugin = "com.google.firebase:firebase-crashlytics-gradle:3.0.8"

[plugins]
android-application = "com.android.application:9.2.1"
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = "io.gitlab.arturbosch.detekt:1.23.8"
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = "com.google.devtools.ksp:2.3.7"