name: Acceptance tests
on: [push]
jobs:
  build:
    runs-on: macos-11 # Switch back to macos-latest when https://github.com/actions/runner-images/issues/6384 is closed
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
        distribution: 'temurin'
        java-version: '11'
      - name: Acceptance Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
