name: Build
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Assemble
        run: ./gradlew clean assembleDebug
      - name: Detekt
        run: ./gradlew detekt
      - name: Lint
        run: ./gradlew lint
      - name: Unit Tests
        run: ./gradlew test
      # - name: Intrumentation Tests
      #  uses: reactivecircus/android-emulator-runner@v2
      #  with:
      #    api-level: 29
      #    target: default
      #    arch: x86
      #    profile: Nexus 6
      #    script: ./gradlew connectedCheck
