name: Assemble, Detekt, Lint and Unit tests
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Assemble, detekt, lint and Unit tests
        run: ./gradlew clean assembleDebug detekt lint test
