name: Assemble, Detekt, Lint and Unit tests
on: [push]
jobs:
  build:
    runs-on: macos-11 # Switch back to macos-latest when https://github.com/actions/runner-images/issues/6384 is closed
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Assemble
        run: ./gradlew clean assembleDebug
      - name: Detekt
        run: ./gradlew clean detekt
      - name: Lint
        run: ./gradlew lint
      - name: Unit Tests
        run: ./gradlew test
      - name: Intrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          # target: default
          # arch: x86
          # profile: Nexus 6
          script: ./gradlew connectedCheck
