name: Assemble, Detekt, Lint and Unit tests
on: [push]
jobs:
  build:
    runs-on: macos-11 # Switch back to macos-latest when https://github.com/actions/runner-images/issues/6384 is closed
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Assemble, detekt, lint and Unit tests
        run: ./gradlew clean assembleDebug detekt lint test
